service: lambda-screenshot
frameworkVersion: "3"
provider:
  name: aws
  runtime: nodejs18.x
# you can overwrite defaults here
  stage: dev
  region: ap-southeast-2
functions:
  captureScreenshot:
    handler: handler.captureScreenshot
    timeout: 60
    environment:
      IS_LOCAL: true
    events:
      - httpApi:
          path: /captureScreenshot
          method: post
# Serverless Offline Configuration
plugins:
  - serverless-offline
custom:
  serverless-offline:
    httpPort: 3000 # Port for local testing